/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ui;

import com.edusys.dao.NhanvienDao;
import com.edusys.entity.Nhanvien;
import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;

/**
 *
 * @author HOANG HUU
 */
public class DangNhap extends javax.swing.JDialog {

	/**
	 * Creates new form DangNhap1
	 */
	public DangNhap(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		init();
	}

	private void init() {
		setIconImage(XImage.getAppIcon());
		setLocationRelativeTo(null);
		setTitle("Đăng Nhập Hệ Thống ");
	}

	NhanvienDao dao = new NhanvienDao();

	void dangNhap() {
		String manv = txtMaNV.getText();
		String matkhau = new String(txtPass.getPassword());
		Nhanvien nv = dao.selectById(manv);

		if (nv == null) {
			MsgBox.alert(this, "Sai tên đăng nhập!");
			txtMaNV.requestFocus();
		} else if (!matkhau.equals(nv.getMatkhau())) {
			MsgBox.alert(this, "Sai mật khẩu!");
			txtPass.requestFocus();
		} else {
			MsgBox.alert(this, "Đăng nhập thành công.");
			Auth.user = nv;
			this.dispose();
			// new EdusysJFrame(null,true).setVisible(true);
		}
	}

	void ketThuc() {
		if (MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng?")) {
			System.exit(0);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		btnDangNhap = new javax.swing.JButton();
		btnKetThuc = new javax.swing.JButton();
		txtPass = new javax.swing.JPasswordField();
		jLabel1 = new javax.swing.JLabel();
		txtMaNV = new javax.swing.JTextField();
		lblHinhAnh = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("Mật Khẩu");

		btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Key.png"))); // NOI18N
		btnDangNhap.setText("Đăng Nhập");
		btnDangNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnDangNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDangNhapActionPerformed(evt);
			}
		});

		btnKetThuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Log out.png"))); // NOI18N
		btnKetThuc.setText("Kết Thúc");
		btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnKetThucActionPerformed(evt);
			}
		});

		txtPass.setText("2003");
		txtPass.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtPassActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("Tên Đăng Nhập");

		txtMaNV.setText("HuuNV");
		txtMaNV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtMaNVActionPerformed(evt);
			}
		});

		lblHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Secure.png"))); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 263,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1)
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jLabel2).addComponent(txtMaNV).addComponent(txtPass,
										javax.swing.GroupLayout.PREFERRED_SIZE, 307,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(18, 18, 18).addComponent(jLabel1)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel2)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(
						txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(btnDangNhap).addComponent(btnKetThuc))
				.addContainerGap(76, Short.MAX_VALUE)).addComponent(lblHinhAnh,
						javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
						Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDangNhapActionPerformed
		// TODO add your handling code here:
		if (txtMaNV.getText().length() == 0) {
			MsgBox.alert(this, "Không được để trống Tên Đăng Nhập!");
			txtMaNV.requestFocus();
		} else if (txtPass.getText().length() == 0) {
			MsgBox.alert(this, "Không được để trống Mật Khẩu!");
			txtPass.requestFocus();
		} else {
			dangNhap();
		}
	}// GEN-LAST:event_btnDangNhapActionPerformed

	private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnKetThucActionPerformed
		// TODO add your handling code here:
		ketThuc();
	}// GEN-LAST:event_btnKetThucActionPerformed

	private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPassActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtPassActionPerformed

	private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMaNVActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtMaNVActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DangNhap dialog = new DangNhap(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDangNhap;
	private javax.swing.JButton btnKetThuc;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel lblHinhAnh;
	public javax.swing.JTextField txtMaNV;
	private javax.swing.JPasswordField txtPass;
	// End of variables declaration//GEN-END:variables
}
