/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ui;

import com.edusys.dao.NhanvienDao;
import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;

/**
 *
 * @author HOANG HUU
 */
public class DoiMatKhau extends javax.swing.JDialog {

	/**
	 * Creates new form DoiMatKhau
	 */
	public DoiMatKhau(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		init();
	}

	private void init() {
		setIconImage(XImage.getAppIcon());
		setLocationRelativeTo(null);
		setTitle("EDUSYS-Đổi mật khẩu");
	}

	NhanvienDao dao = new NhanvienDao();

	void clear() {
		txtTenDangNhap.setText("");
		txtMatKhau.setText("");
		txtMatKhauMoi.setText("");
		txtMatKhauMoi2.setText("");
	}

	private void doiMK() {
		String manv = txtTenDangNhap.getText();
		String matkhau = new String(txtMatKhau.getPassword());
		String matkhauMoi = new String(txtMatKhauMoi.getPassword());
		String matkhauMoi2 = new String(txtMatKhauMoi2.getPassword());

		if (!manv.equalsIgnoreCase(Auth.user.getMaNV())) {
			MsgBox.alert(this, "Sai tên đăng nhập!");
		} else if (!matkhau.equals(Auth.user.getMatkhau())) {
			MsgBox.alert(this, "Sai mật khẩu!");
		} else if (matkhau.equals(matkhauMoi)) {
			MsgBox.alert(this, "Mật khẩu mới không được trùng với mật khẩu hiện tại!");
		} else if (!matkhauMoi.equals(matkhauMoi2)) {
			MsgBox.alert(this, "Xác nhận mật khẩu không đúng!");
		} else {
			Auth.user.setMatkhau(matkhauMoi);
			dao.update(Auth.user);
			MsgBox.alert(this, "Đổi mật khẩu thành công!");
			clear();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtTenDangNhap = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		btnDongy = new javax.swing.JButton();
		btnHuybo = new javax.swing.JButton();
		txtMatKhau = new javax.swing.JPasswordField();
		txtMatKhauMoi2 = new javax.swing.JPasswordField();
		txtMatKhauMoi = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(69, 127, 10));
		jLabel1.setText("Đổi Mật Khẩu");

		jLabel2.setText("Tên đăng nhập");

		jLabel3.setText("Mật khẩu mới");

		jLabel4.setText("Mật khẩu hiện tại");

		jLabel5.setText("Xác nhận mật khẩu mới");

		btnDongy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
		btnDongy.setText("Đồng ý");
		btnDongy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDongyActionPerformed(evt);
			}
		});

		btnHuybo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/No.png"))); // NOI18N
		btnHuybo.setText("Hủy bỏ");
		btnHuybo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHuyboActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(txtTenDangNhap)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtMatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 174,
										Short.MAX_VALUE))
						.addGap(59, 59, 59)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup().addComponent(btnDongy)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18,
												Short.MAX_VALUE)
										.addComponent(btnHuybo))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
										.addComponent(txtMatKhau, javax.swing.GroupLayout.Alignment.LEADING))))
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(jLabel1).addGap(26, 26, 26)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(jLabel4))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(21, 21, 21)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(37, 37, 37)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnDongy).addComponent(btnHuybo))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnDongyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDongyActionPerformed
		if (txtTenDangNhap.getText().length() == 0) {
			MsgBox.alert(this, "Không được để trống Tên Đăng Nhập!");
		} else if (txtMatKhau.getText().length() == 0) {
			MsgBox.alert(this, "Không được để trống Mật Khẩu!");
		} else if (txtMatKhauMoi.getText().length() == 0) {
			MsgBox.alert(this, "Bạn phải nhập Mật Khẩu Mới!");
		} else if (txtMatKhauMoi2.getText().length() == 0) {
			MsgBox.alert(this, "Bạn phải xác nhận mật khẩu!");
		} else {
			doiMK();
		}
	}// GEN-LAST:event_btnDongyActionPerformed

	private void btnHuyboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuyboActionPerformed
		this.dispose();
	}// GEN-LAST:event_btnHuyboActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DoiMatKhau dialog = new DoiMatKhau(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDongy;
	private javax.swing.JButton btnHuybo;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPasswordField txtMatKhau;
	private javax.swing.JPasswordField txtMatKhauMoi;
	private javax.swing.JPasswordField txtMatKhauMoi2;
	private javax.swing.JTextField txtTenDangNhap;
	// End of variables declaration//GEN-END:variables
}
