/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ui;

import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.security.auth.AuthPermission;
import javax.swing.Timer;
import javax.swing.plaf.DesktopPaneUI;

/**
 *
 * @author HOANG HUU
 */
public class EdusysJFrame extends javax.swing.JDialog {

	/**
	 * Creates new form EdusysJFrame
	 */
	public EdusysJFrame(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		init();
	}

	private void init() {
		setSize(1650, 1080);
		setIconImage(XImage.getAppIcon());
		setLocationRelativeTo(null);
		setTitle("Hệ Thống Quản Lý Đào Tạo EDUSYS");
		new Timer(1000, new ActionListener() {
			SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");
			@Override
			public void actionPerformed(ActionEvent e) {
				lblDongho.setText(format.format(new Date()));
			}
		}).start();
		this.openWelcome();
		this.openLogin();
	}

	void openWelcome() {
		new chao(null, true).setVisible(true);
	}

	void openLogin() {
		new DangNhap(null, true).setVisible(true);
	}

	void openDoiMatKhau() {
		if (Auth.isLogin()) {
			new DoiMatKhau(null, true).setVisible(true);
		} else {
			MsgBox.alert(this, "Vui lòng đăng nhập!");
		}

	}

	void dangXuat() {
		if (MsgBox.confirm(this, "Bạn có muốn đăng xuất không?")) {
			Auth.clear();
			MsgBox.alert(this, "Đăng xuất thành công.");
			this.dispose();
			new DangNhap(null, true).setVisible(true);
			
		}
	}

	void ketThuc() {
		if (MsgBox.confirm(this, "Bạn có muốn kết thúc chương trình?")) {
			System.exit(0);
		}
	}

	void openNhanVien() {
		if (Auth.isLogin()) {
			NhanVienform frame = new NhanVienform(null, true);
			frame.setVisible(true);
		}
	}

	void openChuyenDe() {
		if (Auth.isLogin()) {
			ChuyenDeForm frame = new ChuyenDeForm(null, true);
			frame.setVisible(true);
		}
	}

	void openHocVien() {
		if (Auth.isLogin()) {
			HocVienForm frame = new HocVienForm(null, true);
			frame.setVisible(true);
		}
	}

	void openKhoaHoc() {
		if (Auth.isLogin()) {
			new KhoahocForm(null, true).setVisible(true);
		}
	}

	void openGioiThieu() {
		if (Auth.isLogin()) {
			new GioiThieuJDialog(null, true).setVisible(true);
		}
	}

	void openHuongDan() {
		try {
			Desktop.getDesktop().browse(new File("help/code.html").toURI());
		} catch (IOException ex) {
			MsgBox.alert(this, "Không tìm thấy file hướng dẫn!");
		}

	}

	void openNguoiHoc() {
		if (Auth.isLogin()) {
			new NguoiHocForm(null, true).setVisible(true);
		}
	}

	void openThongKe(int index) {
		if (Auth.isLogin()) {
			if (index == 3 && !Auth.isManager()) {
				MsgBox.alert(this, "Bạn không có quyền xem doanh thu!!!");
			} else {
				ThongKeForm frame = new ThongKeForm(null, true);
				frame.setVisible(true);
				frame.selectTab(index);
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jToolBar1 = new javax.swing.JToolBar();
		btnDangxuat = new javax.swing.JButton();
		btnKetthuc = new javax.swing.JButton();
		jSeparator2 = new javax.swing.JToolBar.Separator();
		btnChuyende = new javax.swing.JButton();
		btnNguoihoc = new javax.swing.JButton();
		btnKhoahoc = new javax.swing.JButton();
		btnHocvien = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JToolBar.Separator();
		btnHuongdan = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		lblTrangthai = new javax.swing.JLabel();
		lblDongho = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		mnHethong = new javax.swing.JMenu();
		mnlDoimatkhau = new javax.swing.JMenuItem();
		mnlDangxuat = new javax.swing.JMenuItem();
		mnlKetthuc = new javax.swing.JMenuItem();
		mnQuanly = new javax.swing.JMenu();
		mnlChuyende = new javax.swing.JMenuItem();
		mnlKhoahoc = new javax.swing.JMenuItem();
		mnlNguoihoc = new javax.swing.JMenuItem();
		mnlHocvien = new javax.swing.JMenuItem();
		mnlNhanvien = new javax.swing.JMenuItem();
		mnThongke = new javax.swing.JMenu();
		mniBangdiem = new javax.swing.JMenuItem();
		mnlLuongnguoihoc = new javax.swing.JMenuItem();
		mnlDiemchuyende = new javax.swing.JMenuItem();
		mnlDoangthu = new javax.swing.JMenuItem();
		mnTrogiup = new javax.swing.JMenu();
		mnlHuongdan = new javax.swing.JMenuItem();
		mnlGioithieu = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jToolBar1.setBackground(new java.awt.Color(182, 248, 233));
		jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jToolBar1.setRollover(true);

		btnDangxuat.setBackground(new java.awt.Color(182, 248, 233));
		btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Log out.png"))); // NOI18N
		btnDangxuat.setText("Đăng Xuất");
		btnDangxuat.setFocusable(false);
		btnDangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnDangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlDangxuatActionPerformed(evt);
			}
		});
		jToolBar1.add(btnDangxuat);

		btnKetthuc.setBackground(new java.awt.Color(182, 248, 233));
		btnKetthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
		btnKetthuc.setText("Kết thúc");
		btnKetthuc.setBorder(null);
		btnKetthuc.setFocusable(false);
		btnKetthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnKetthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnKetthuc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlKetthucActionPerformed(evt);
			}
		});
		jToolBar1.add(btnKetthuc);
		jToolBar1.add(jSeparator2);

		btnChuyende.setBackground(new java.awt.Color(182, 248, 233));
		btnChuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
		btnChuyende.setText("Chuyên dề");
		btnChuyende.setFocusable(false);
		btnChuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnChuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnChuyende.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnChuyendeActionPerformed(evt);
			}
		});
		jToolBar1.add(btnChuyende);

		btnNguoihoc.setBackground(new java.awt.Color(182, 248, 233));
		btnNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Conference.png"))); // NOI18N
		btnNguoihoc.setText("Người học");
		btnNguoihoc.setFocusable(false);
		btnNguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnNguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnNguoihoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNguoihocActionPerformed(evt);
			}
		});
		jToolBar1.add(btnNguoihoc);

		btnKhoahoc.setBackground(new java.awt.Color(182, 248, 233));
		btnKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Certificate.png"))); // NOI18N
		btnKhoahoc.setText("Khóa học");
		btnKhoahoc.setFocusable(false);
		btnKhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnKhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnKhoahoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnKhoahocActionPerformed(evt);
			}
		});
		jToolBar1.add(btnKhoahoc);

		btnHocvien.setBackground(new java.awt.Color(182, 248, 233));
		btnHocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
		btnHocvien.setText("Học viên");
		btnHocvien.setFocusable(false);
		btnHocvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnHocvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnHocvien.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHocvienActionPerformed(evt);
			}
		});
		jToolBar1.add(btnHocvien);
		jToolBar1.add(jSeparator1);

		btnHuongdan.setBackground(new java.awt.Color(182, 248, 233));
		btnHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Globe.png"))); // NOI18N
		btnHuongdan.setText("Hướng dẫn");
		btnHuongdan.setFocusable(false);
		btnHuongdan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btnHuongdan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		btnHuongdan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHuongdanActionPerformed(evt);
			}
		});
		jToolBar1.add(btnHuongdan);

		jPanel2.setBackground(new java.awt.Color(245, 245, 255));

		jLabel1.setBackground(java.awt.Color.darkGray);
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(233, 233, 233)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(63, 63, 63)));

		jPanel1.setBackground(new java.awt.Color(245, 245, 255));
		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		lblTrangthai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Info.png"))); // NOI18N
		lblTrangthai.setText("Hệ Quản Lý Đào Tạo");

		lblDongho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alarm.png"))); // NOI18N
		lblDongho.setText("00:00:AM");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(lblTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(lblDongho, javax.swing.GroupLayout.PREFERRED_SIZE, 133,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTrangthai).addComponent(lblDongho))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jMenuBar1.setBackground(new java.awt.Color(204, 255, 204));

		mnHethong.setBackground(new java.awt.Color(204, 255, 204));
		mnHethong.setText("Hệ thống");

		mnlDoimatkhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
		mnlDoimatkhau.setBackground(new java.awt.Color(204, 255, 204));
		mnlDoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
		mnlDoimatkhau.setText("Đổi Mật Khẩu");
		mnlDoimatkhau.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlDoimatkhauActionPerformed(evt);
			}
		});
		mnHethong.add(mnlDoimatkhau);

		mnlDangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O,
				java.awt.event.InputEvent.CTRL_DOWN_MASK));
		mnlDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Log out.png"))); // NOI18N
		mnlDangxuat.setText("Đăng Xuất");
		mnlDangxuat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlDangxuatActionPerformed(evt);
			}
		});
		mnHethong.add(mnlDangxuat);

		mnlKetthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
		mnlKetthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Stop.png"))); // NOI18N
		mnlKetthuc.setText("Kết Thúc");
		mnlKetthuc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlKetthucActionPerformed(evt);
			}
		});
		mnHethong.add(mnlKetthuc);

		jMenuBar1.add(mnHethong);

		mnQuanly.setText("Quản lý");

		mnlChuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1,
				java.awt.event.InputEvent.CTRL_DOWN_MASK));
		mnlChuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
		mnlChuyende.setText("Chuyên Đề");
		mnlChuyende.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnChuyendeActionPerformed(evt);
			}
		});
		mnQuanly.add(mnlChuyende);

		mnlKhoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2,
				java.awt.event.InputEvent.CTRL_DOWN_MASK));
		mnlKhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Certificate.png"))); // NOI18N
		mnlKhoahoc.setText("Khóa Học");
		mnlKhoahoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnKhoahocActionPerformed(evt);
			}
		});
		mnQuanly.add(mnlKhoahoc);

		mnlNguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3,
				java.awt.event.InputEvent.CTRL_DOWN_MASK));
		mnlNguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Conference.png"))); // NOI18N
		mnlNguoihoc.setText("Người Học");
		mnlNguoihoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnNguoihocActionPerformed(evt);
			}
		});
		mnQuanly.add(mnlNguoihoc);

		mnlHocvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4,
				java.awt.event.InputEvent.CTRL_DOWN_MASK));
		mnlHocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User.png"))); // NOI18N
		mnlHocvien.setText("Học Viên");
		mnlHocvien.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHocvienActionPerformed(evt);
			}
		});
		mnQuanly.add(mnlHocvien);

		mnlNhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5,
				java.awt.event.InputEvent.CTRL_DOWN_MASK));
		mnlNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User group.png"))); // NOI18N
		mnlNhanvien.setText("Nhân Viên");
		mnlNhanvien.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlNhanvienActionPerformed(evt);
			}
		});
		mnQuanly.add(mnlNhanvien);

		jMenuBar1.add(mnQuanly);

		mnThongke.setText("Thống kê");

		mniBangdiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1,
				java.awt.event.InputEvent.SHIFT_DOWN_MASK));
		mniBangdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Card file.png"))); // NOI18N
		mniBangdiem.setText("Bảng Điểm");
		mniBangdiem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mniBangdiemActionPerformed(evt);
			}
		});
		mnThongke.add(mniBangdiem);

		mnlLuongnguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2,
				java.awt.event.InputEvent.SHIFT_DOWN_MASK));
		mnlLuongnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clien list.png"))); // NOI18N
		mnlLuongnguoihoc.setText("Lượng Người Học");
		mnlLuongnguoihoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlLuongnguoihocActionPerformed(evt);
			}
		});
		mnThongke.add(mnlLuongnguoihoc);

		mnlDiemchuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3,
				java.awt.event.InputEvent.SHIFT_DOWN_MASK));
		mnlDiemchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Statistics.png"))); // NOI18N
		mnlDiemchuyende.setText("Điểm Chuyên Đề");
		mnlDiemchuyende.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlDiemchuyendeActionPerformed(evt);
			}
		});
		mnThongke.add(mnlDiemchuyende);

		mnlDoangthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4,
				java.awt.event.InputEvent.SHIFT_DOWN_MASK));
		mnlDoangthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dollar.png"))); // NOI18N
		mnlDoangthu.setText("Doanh Thu");
		mnlDoangthu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlDoangthuActionPerformed(evt);
			}
		});
		mnThongke.add(mnlDoangthu);

		jMenuBar1.add(mnThongke);

		mnTrogiup.setBackground(new java.awt.Color(255, 255, 204));
		mnTrogiup.setText("Trợ giúp");
		mnTrogiup.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHuongdanActionPerformed(evt);
			}
		});

		mnlHuongdan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
		mnlHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Globe.png"))); // NOI18N
		mnlHuongdan.setText("Hướng Dẫn Sử Dụng");
		mnlHuongdan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHuongdanActionPerformed(evt);
			}
		});
		mnTrogiup.add(mnlHuongdan);

		mnlGioithieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
		mnlGioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home.png"))); // NOI18N
		mnlGioithieu.setText("Giới Thiệu Sản Phẩm");
		mnlGioithieu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				mnlGioithieuActionPerformed(evt);
			}
		});
		mnTrogiup.add(mnlGioithieu);

		jMenuBar1.add(mnTrogiup);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void mnlDoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnlDoimatkhauActionPerformed
		openDoiMatKhau();
	}// GEN-LAST:event_mnlDoimatkhauActionPerformed

	private void mnlDangxuatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnlDangxuatActionPerformed
		dangXuat();
	}// GEN-LAST:event_mnlDangxuatActionPerformed

	private void mnlKetthucActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnlKetthucActionPerformed
		ketThuc();
	}// GEN-LAST:event_mnlKetthucActionPerformed

	private void mnlNhanvienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnlNhanvienActionPerformed
		openNhanVien();
	}// GEN-LAST:event_mnlNhanvienActionPerformed

	private void btnChuyendeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChuyendeActionPerformed
		openChuyenDe();
	}// GEN-LAST:event_btnChuyendeActionPerformed

	private void btnHocvienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHocvienActionPerformed
		openHocVien();
	}// GEN-LAST:event_btnHocvienActionPerformed

	private void mnlGioithieuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnlGioithieuActionPerformed
		openGioiThieu();
	}// GEN-LAST:event_mnlGioithieuActionPerformed

	private void btnKhoahocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnKhoahocActionPerformed
		openKhoaHoc();
	}// GEN-LAST:event_btnKhoahocActionPerformed

	private void btnHuongdanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuongdanActionPerformed
		openHuongDan();
	}// GEN-LAST:event_btnHuongdanActionPerformed

	private void btnNguoihocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNguoihocActionPerformed
		openNguoiHoc();
	}// GEN-LAST:event_btnNguoihocActionPerformed

	private void mniBangdiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mniBangdiemActionPerformed
		openThongKe(0);
	}// GEN-LAST:event_mniBangdiemActionPerformed

	private void mnlLuongnguoihocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnlLuongnguoihocActionPerformed
		openThongKe(1);
	}// GEN-LAST:event_mnlLuongnguoihocActionPerformed

	private void mnlDiemchuyendeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnlDiemchuyendeActionPerformed
		openThongKe(2);
	}// GEN-LAST:event_mnlDiemchuyendeActionPerformed

	private void mnlDoangthuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mnlDoangthuActionPerformed
		openThongKe(3);
	}// GEN-LAST:event_mnlDoangthuActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EdusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EdusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EdusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EdusysJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				EdusysJFrame dialog = new EdusysJFrame(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnChuyende;
	private javax.swing.JButton btnDangxuat;
	private javax.swing.JButton btnHocvien;
	private javax.swing.JButton btnHuongdan;
	private javax.swing.JButton btnKetthuc;
	private javax.swing.JButton btnKhoahoc;
	private javax.swing.JButton btnNguoihoc;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JToolBar.Separator jSeparator1;
	private javax.swing.JToolBar.Separator jSeparator2;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JLabel lblDongho;
	private javax.swing.JLabel lblTrangthai;
	private javax.swing.JMenu mnHethong;
	private javax.swing.JMenu mnQuanly;
	private javax.swing.JMenu mnThongke;
	private javax.swing.JMenu mnTrogiup;
	private javax.swing.JMenuItem mniBangdiem;
	private javax.swing.JMenuItem mnlChuyende;
	private javax.swing.JMenuItem mnlDangxuat;
	private javax.swing.JMenuItem mnlDiemchuyende;
	private javax.swing.JMenuItem mnlDoangthu;
	private javax.swing.JMenuItem mnlDoimatkhau;
	private javax.swing.JMenuItem mnlGioithieu;
	private javax.swing.JMenuItem mnlHocvien;
	private javax.swing.JMenuItem mnlHuongdan;
	private javax.swing.JMenuItem mnlKetthuc;
	private javax.swing.JMenuItem mnlKhoahoc;
	private javax.swing.JMenuItem mnlLuongnguoihoc;
	private javax.swing.JMenuItem mnlNguoihoc;
	private javax.swing.JMenuItem mnlNhanvien;
	// End of variables declaration//GEN-END:variables
}
